# Generated by Django 4.2.13 on 2026-05-28 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("ANALYST", "Analyst")],
                        default="ANALYST",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "db_table": "org_user",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (Fuel & Procurement)"),
                            ("UTILITY", "Utility (Electricity Bills)"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("external_ref", models.CharField(blank=True, max_length=255)),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reporting_year", models.PositiveSmallIntegerField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.JSONField(blank=True, null=True)),
                (
                    "ingested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingested_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "esg_data_source",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "active_reporting_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "org_organization",
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                (
                    "source_row_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("checksum", models.CharField(max_length=64)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_records",
                        to="emissions.datasource",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_records",
                        to="emissions.organization",
                    ),
                ),
            ],
            options={
                "db_table": "esg_raw_record",
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporting_year", models.PositiveSmallIntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (Fuel & Procurement)"),
                            ("UTILITY", "Utility (Electricity Bills)"),
                            ("TRAVEL", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1 — Direct"),
                            ("SCOPE_2", "Scope 2 — Indirect (Energy)"),
                            ("SCOPE_3", "Scope 3 — Value Chain"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("quantity_raw", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit_raw", models.CharField(max_length=50)),
                (
                    "quantity_normalized",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "unit_normalized",
                    models.CharField(
                        choices=[
                            ("kg_CO2e", "Kilograms CO₂-equivalent"),
                            ("tCO2e", "Metric Tonnes CO₂-equivalent"),
                            ("kWh", "Kilowatt-hours"),
                            ("MJ", "Megajoules"),
                            ("L", "Litres"),
                            ("km", "Kilometres"),
                            ("night", "Hotel night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emission_factor",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "emission_factor_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("co2e_kg", models.DecimalField(decimal_places=4, max_digits=20)),
                ("confidence_score", models.SmallIntegerField(default=100)),
                ("anomaly_flag", models.BooleanField(default=False)),
                ("anomaly_reason", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVED", "Auto-Approved"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("LOCKED", "Locked (Audited)"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emission_records",
                        to="emissions.datasource",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emission_records",
                        to="emissions.organization",
                    ),
                ),
                (
                    "raw_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emission_records",
                        to="emissions.rawrecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "esg_emission_record",
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sources",
                to="emissions.organization",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("action", models.CharField(max_length=50)),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("before_value", models.JSONField(blank=True, null=True)),
                ("after_value", models.JSONField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="emissions.organization",
                    ),
                ),
            ],
            options={
                "db_table": "esg_audit_log",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="emissions.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(
                fields=["organization", "data_source"],
                name="esg_raw_rec_organiz_e7e619_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(
                fields=["checksum"], name="esg_raw_rec_checksu_0745e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(fields=["raw_payload"], name="gin_raw_payload"),
        ),
        migrations.AddConstraint(
            model_name="rawrecord",
            constraint=models.UniqueConstraint(
                fields=("data_source", "checksum"), name="uq_raw_record_source_checksum"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "reporting_year", "scope"],
                name="esg_emissio_organiz_599e87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "review_status"],
                name="esg_emissio_organiz_11d3da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organization", "source_type", "reporting_year"],
                name="esg_emissio_organiz_4db12a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["anomaly_flag"], name="esg_emissio_anomaly_b1dbcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="esg_emissio_period__1086c7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrecord",
            constraint=models.UniqueConstraint(
                fields=("raw_record", "scope"), name="uq_emission_record_raw_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrecord",
            constraint=models.CheckConstraint(
                check=models.Q(("period_end__gte", models.F("period_start"))),
                name="chk_period_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("confidence_score__gte", 0), ("confidence_score__lte", 100)
                ),
                name="chk_confidence_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrecord",
            constraint=models.CheckConstraint(
                check=models.Q(("co2e_kg__gte", 0)), name="chk_co2e_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["organization", "source_type", "reporting_year"],
                name="esg_data_so_organiz_8c7f05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["ingestion_status"], name="esg_data_so_ingesti_f18152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="esg_audit_l_object__2e2889_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "changed_at"],
                name="esg_audit_l_organiz_3a0bd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["changed_by"], name="esg_audit_l_changed_b35e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "role"], name="org_user_organiz_aad605_idx"
            ),
        ),
    ]
